feat(website): setup sidebar labels and position
privacy-scaling-explorations/maci pull request #1067
Opened 2024-01-19 21:36 UTC by kittybest

# Description

Setup sidebar position and label by adding scripts.

## Related issue(s)

close #921 

## Confirmation

- [ ] I have read and understand MACI's [contributor guidelines](https://maci.pse.dev/docs/contributing) and [code of conduct](https://maci.pse.dev/docs/contributing/code-of-conduct).
- [ ] I have read and understand MACI's [GitHub processes](https://github.com/privacy-scaling-explorations/maci/discussions/847).
- [ ] I have read and understand MACI's [testing guide](https://maci.pse.dev/docs/testing).

2024-01-22 17:22 UTC, kittybest commented
Remaining problem is the index page for **solidity docs** and **typedoc**, they're empty now, but I think there should be some content indicating what these following files are.

2024-01-22 17:37 UTC, ctrlc03 commented
> Remaining problem is the index page for **solidity docs** and **typedoc**, they're empty now, but I think there should be some content indicating what these following files are.

Are you going to tackle that in a separate PR?

2024-01-22 17:47 UTC, 0xmad requested changes
@kittybest thanks, just few comments about code conventions.

2024-01-22 17:47 UTC, 0xmad commented on website/src/scripts/setupTypedoc.ts
> +  fs.writeFileSync(file, `${sidebarInfo}\n${writtenContent}`);
```suggestion
  const content = fs.readFileSync(file).toString().split("\n");

  if (content.length > 3) {
    content.shift();
    content.shift();
    content.shift();
  }

  const writtenContent = content.join("\n").replaceAll("README.md", "index.md");
  fs.writeFileSync(file, `${sidebarInfo}\n${writtenContent}`);
```

2024-01-22 17:47 UTC, 0xmad commented on website/src/scripts/setupTypedoc.ts
> +  const dirname = path.join(TYPEDOC_DIR, dir);
Let's use path resolve instead of join.

2024-01-22 17:47 UTC, 0xmad commented on website/src/scripts/utils.ts
> +interface sidebarProps {
```suggestion
interface SidebarProps {
```

2024-01-22 17:47 UTC, 0xmad commented on website/src/scripts/utils.ts
> +  return ret;
Let's add new lines between conditions.

2024-01-22 17:47 UTC, 0xmad commented on website/src/scripts/utils.ts
> +  return str[0].toUpperCase() + str.slice(1, str.length).toLowerCase();
```suggestion
  return `${str[0].toUpperCase()}${str.slice(1, str.length).toLowerCase()}`;
```

2024-01-22 17:47 UTC, 0xmad commented on website/src/scripts/setupTypedoc.ts
> +    }
```suggestion
  if (fs.statSync(dirname).isDirectory()) {
    const readmeFile = path.resolve(dirname, "README.md");

    if (fs.existsSync(readmeFile)) {
      updateMdFiles(readmeFile, generateSidebarString({ title: label, label }));
      fs.renameSync(readmeFile, path.join(dirname, "index.md"));
    }

    // remove the first two lines of navigator
    const modulesFile = path.resolve(dirname, "modules.md");

    if (fs.existsSync(modulesFile)) {
      updateMdFiles(modulesFile, generateSidebarString({ title: `${label} Module`, label: "module", position: 1 }));
    }
```

2024-01-22 17:47 UTC, 0xmad commented on website/src/scripts/setupTypedoc.ts
> +    });
```suggestion
    const innerDirs = fs.readdirSync(dirname);

    innerDirs.forEach((innerDir) => {
      const innerDirname = path.join(dirname, innerDir);

      if (fs.statSync(innerDirname).isDirectory()) {
        const innerFiles = fs.readdirSync(innerDirname);
        innerFiles.forEach((innerFile) => {
          const innerLabel = innerFile.split(".")[0];
          updateMdFiles(
            path.join(innerDirname, innerFile),
            generateSidebarString({ title: innerLabel, label: innerLabel }),
          );
        });
      }
    });
```

2024-01-22 19:08 UTC, kittybest commented
> > Remaining problem is the index page for **solidity docs** and **typedoc**, they're empty now, but I think there should be some content indicating what these following files are.
> 
> Are you going to tackle that in a separate PR?

Yes I think so, since there's also another separate issue #922 . This PR could just for #921.

2024-01-22 19:11 UTC, kittybest commented on website/src/scripts/setupTypedoc.ts
> +  const dirname = path.join(TYPEDOC_DIR, dir);
For all of them, or just this?

2024-01-23 15:19 UTC, 0xmad commented on website/src/scripts/setupTypedoc.ts
> +  const dirname = path.join(TYPEDOC_DIR, dir);
Right, for all of them.

2024-01-23 16:17 UTC, 0xmad approved these changes
@kittybest thanks!

2024-01-23 17:47 UTC, merged