Docs/gatekeeper page
privacy-scaling-explorations/maci pull request #1443
Opened 2024-05-08 22:53 UTC by samajammin

# Description

Add gatekeeper docs page

## Related issue(s)

Fixes #1382

## Confirmation

- [x] I have read and understand MACI's [contributor guidelines](https://maci.pse.dev/docs/contributing) and [code of conduct](https://maci.pse.dev/docs/contributing/code-of-conduct).
- [x] I have read and understand MACI's [GitHub processes](https://github.com/privacy-scaling-explorations/maci/discussions/847).
- [x] I have read and understand MACI's [testing guide](https://maci.pse.dev/docs/testing).

2024-05-09 06:43 UTC, ctrlc03 requested changes
Thanks! left some comments

2024-05-09 06:43 UTC, ctrlc03 commented on website/versioned_docs/version-v1.3_alpha/contracts/contracts.md
> +MACI requires a gatekeeper cont ract to ensure that only eligible users can register.
seems like there's a space in the word "contract"

2024-05-09 06:43 UTC, ctrlc03 commented on website/versioned_docs/version-v1.3_alpha/contracts/gatekeepers.md
> +MACI uses a "gatekeeper" contract, which is used to configure and enforce the eligibility criteria of voters who can participate in MACI polls. In other words, it is a way to whitelist signups to the
typo: "agaisnt"

2024-05-09 06:43 UTC, ctrlc03 commented on website/versioned_docs/version-v1.3_alpha/contracts/gatekeepers.md
> +Whenever a user signs, up (via the `MACI.signUp` function), this triggers the MACI contract to call the `SignUpGatekeeper.register` function.
no comma between "signs" and "up"

2024-05-09 06:43 UTC, ctrlc03 commented on website/versioned_docs/version-v1.3_alpha/contracts/gatekeepers.md
> +Whenever a user signs, up (via the `MACI.signUp` function), this triggers the MACI contract to call the `SignUpGatekeeper.register` function.
it's important to add that the `SigupGatekeeper.register` function should either return successfully or revert on error - it should not be returning true or false

2024-05-22 14:33 UTC, samajammin commented
@ctrlc03 if you or someone else has bandwidth to make changes & merge, I'd be grateful 🙏

2024-05-22 15:18 UTC, ctrlc03 commented
> @ctrlc03 if you or someone else has bandwidth to make changes & merge, I'd be grateful 🙏

changes made, will need a review please

2024-05-22 16:06 UTC, 0xmad approved these changes
@samajammin @ctrlc03 thanks!

2024-05-22 16:15 UTC, kittybest commented on website/versioned_docs/version-v2.0_alpha/developers-references/smart-contracts/Gatekeepers.md
> +Developers are also welcome to implement a custom gatekeeper contracts as long as it conforms to the `SignUpGatekeeper` - an abstract contract to inherit from with two function signatures:
nit: contracts --> contract

2024-05-22 16:31 UTC, ctrlc03 approved these changes

2024-05-22 16:31 UTC, merged