chore: prepare for release
privacy-scaling-explorations/maci pull request #1722
Opened 2024-08-01 20:22 UTC by 0xmad

# Description

- [x] Add new download link for test artifacts
- [x] Update website docs

## Additional Notes

N/A

## Related issue(s)

Closes #1614 

## Confirmation

- [x] I have read and understand MACI's [contributor guidelines](https://maci.pse.dev/docs/contributing) and [code of conduct](https://maci.pse.dev/docs/contributing/code-of-conduct).
- [x] I have read and understand MACI's [GitHub processes](https://github.com/privacy-scaling-explorations/maci/discussions/847).
- [x] I have read and understand MACI's [testing guide](https://maci.pse.dev/docs/testing).

2024-08-01 20:28 UTC, ctrlc03 requested changes
Thanks, left some comments, also let's bump to 2.0 on the various package.json from 2_alpha?

2024-08-01 20:28 UTC, ctrlc03 commented on website/.gitignore
>  versioned_docs/version-v2.0_alpha/developers-references/typescript-code/typedoc/
should we remove those 2?

2024-08-01 20:28 UTC, ctrlc03 commented on website/versions.json
> +["v2.x", "v1.2", "v0.x"]
not sure if it's just me but I cannot see the left navigation bar for the docs on v2.x

2024-08-01 20:46 UTC, ctrlc03 commented on website/versions.json
> +["v2.x", "v1.2", "v0.x"]
nice, it shows now for me too, not sure what happened there haha

2024-08-02 17:08 UTC, kittybest approved these changes
Thanks!

2024-08-06 02:15 UTC, 0xmad commented
Let's wait for audit report updates

2024-08-06 16:10 UTC, ctrlc03 approved these changes

2024-08-06 16:10 UTC, merged