docs(blogpost): poll joining blog
privacy-scaling-explorations/maci pull request #1798
Opened 2024-08-30 13:40 UTC by djanluka

# Description

PR with a blogpost of the Anonymous poll joining grant.

## Related issue(s)

The blogpost for #1566 

## Confirmation

- [x] I have read and understand MACI's [contributor guidelines](https://maci.pse.dev/docs/contributing) and [code of conduct](https://maci.pse.dev/docs/contributing/code-of-conduct).
- [x] I have read and understand MACI's [GitHub processes](https://github.com/privacy-scaling-explorations/maci/discussions/847).
- [x] I have read and understand MACI's [testing guide](https://maci.pse.dev/docs/testing).

2024-08-30 16:25 UTC, ctrlc03 reviewed
Seems like there's some build error, try inside `apps/website` to run `pnpm build` please

2024-09-02 08:58 UTC, ctrlc03 requested changes
LGTM, just one typo

2024-09-02 08:58 UTC, ctrlc03 commented on apps/website/blog/2024-08-29-poll-joining.md
> +Poll joining represents a protocol change where each poll contains its own poll state tree that stores the keys of users who want to vote on that poll. The users join the poll by providing a new key
typo: "correctly computer" -> "correctly computed"

2024-09-02 09:25 UTC, djanluka commented on apps/website/blog/2024-08-29-poll-joining.md
> +title: Poll joining improves anonymity - but wait, there is more!
It sounds me better too, I'll update

2024-09-02 09:29 UTC, djanluka commented on apps/website/blog/2024-08-29-poll-joining.md
> +title: Poll joining improves anonymity - but wait, there is more!
https://github.com/privacy-scaling-explorations/maci/pull/1798/commits/84a45bf5802cec69bdbc9b8da32624307d8f992c

2024-09-02 09:29 UTC, djanluka commented on apps/website/blog/2024-08-29-poll-joining.md
> +Poll joining represents a protocol change where each poll contains its own poll state tree that stores the keys of users who want to vote on that poll. The users join the poll by providing a new key
https://github.com/privacy-scaling-explorations/maci/pull/1798/commits/6d27f6fe0a9eb48a3d7bed060a535877ee199baf

2024-09-02 09:33 UTC, ctrlc03 approved these changes
🚀

2024-09-02 09:52 UTC, ctrlc03 commented
@djanluka not sure what happened but I cannot rebase it from the ui, could you please rebase this branch to dev so it will let me merge it?

2024-09-02 10:01 UTC, ctrlc03 commented
now there's 11 commits, please use rebase 

<img width="1340" alt="Screenshot 2024-09-02 at 10 59 42" src="https://github.com/user-attachments/assets/74de9ddc-cc2d-444b-9266-590a53639143">

2024-09-02 10:26 UTC, djanluka commented
I pulled `dev` into `blog/poll-joining`, but had `pull.rebase false` in the git config.. Could you merge with 11 commits?

2024-09-02 10:29 UTC, ctrlc03 commented
> I pulled dev into blog/poll-joining, but had pull.rebase false in the git config.. Could you merge with 11 commits? @ctrlc03

@djanluka So we don't use merge, we use rebase in this repo. If you see, now this PR is trying to merge files that are already part of the codebase and have nothing to do with the blogpost. Please cleanup the PR and ensure that only the relevant commits and files are part of it.

2024-09-02 10:31 UTC, kittybest approved these changes
thanks!

Meanwhile, I suggest squash all the commits in this PR before you rebase, that would make your day better.

2024-09-02 12:46 UTC, djanluka commented
I reverted unnecessary changes, but you still can't rebase?

2024-09-02 13:12 UTC, ctrlc03 commented
> I reverted unnecessary changes, but you still can't rebase?

please run 

```
git reset $(git merge-base dev $(git rev-parse --abbrev-ref HEAD))
```

and force push so there is only one commit and a clean history

2024-09-02 13:36 UTC, djanluka commented
> (git rev-parse --abbrev-ref HEAD

done, but again there are 7 files changed

2024-09-02 13:39 UTC, djanluka commented
if doesn't work for you, we might raise a new clear pull request?

2024-09-02 14:26 UTC, closed without merging