refactor: Redesigned projects built with MACI
privacy-scaling-explorations/maci pull request #1813
Opened 2024-09-07 03:15 UTC by MukulKolpe

# Description

Redesigned the MACI projects page to improve user interface and make it easier to update when new projects are added.

https://github.com/user-attachments/assets/3eb40c77-260c-4e21-9b12-08f4f4dafb1c

## Additional Notes

## Related issue(s)

Fixes #1613

## Confirmation

- [x] I have read and understand MACI's [contributor guidelines](https://maci.pse.dev/docs/contributing) and [code of conduct](https://maci.pse.dev/docs/contributing/code-of-conduct).
- [x] I have read and understand MACI's [GitHub processes](https://github.com/privacy-scaling-explorations/maci/discussions/847).
- [x] I have read and understand MACI's [testing guide](https://maci.pse.dev/docs/testing).

2024-09-07 03:20 UTC, MukulKolpe commented
Hey @ctrlc03, sorry for the delay. Please let me know if any adjustments are needed regarding themes, wording, conventions, etc.

2024-09-08 06:27 UTC, ctrlc03 requested changes
This looks amazing thank you very much 🚀 

Could you please ensure linter checks are passed (you can run locally with `pnpm lint:ts:fix`) and also it seems like navigation buttons are not displaying correctly in light mode, and the cards and text also

2024-09-08 06:27 UTC, ctrlc03 commented on apps/website/src/content/projects.json
> +    "name": "MACI-RPGF",
can we change this to MACI Platform

2024-09-08 06:27 UTC, ctrlc03 commented on apps/website/src/content/projects.json
> +    "description": "a fork from Easy-RPGF that enables any community to easily run an RPGF round using MACI.",
can we change this to: a platform that allows to run different types of vote and funding rounds using MACI.

2024-09-09 12:44 UTC, kittybest commented
I think the light mode color should be adjusted, other things are perfect! thanks! 

<img width="1374" alt="image" src="https://github.com/user-attachments/assets/c6f9b508-9fe3-4707-9d7e-69a1678e2d00">

2024-09-10 09:51 UTC, MukulKolpe commented
Thank you @ctrlc03 @kittybest! Please let me know if any other changes are needed.

https://github.com/user-attachments/assets/bb9baba3-9768-4201-a92f-2c4368bdb3c4

2024-09-11 19:00 UTC, ctrlc03 commented
@MukulKolpe seems like you used merge rather than rebase, please squash your commits and rebase to the latest dev :)

2024-09-12 02:22 UTC, kittybest approved these changes
It looks so nice, thanks a lot!

2024-09-12 03:07 UTC, ctrlc03 commented on pnpm-lock.yaml
> +=======
there's conflict markers here

2024-09-12 05:03 UTC, merged