feat(scripts): add MACI key generation script
privacy-scaling-explorations/maci pull request #1869
Opened 2024-10-23 23:30 UTC by programmerraja

# Description
add MACI key generation script
    - Add generateMaciKeys.js script
    - Update package.json with new script command
    - Update .gitignore to exclude maci-keys directory

## Additional Notes

## Related issue(s)

## Confirmation

- [ ] I have read and understand MACI's [contributor guidelines](https://maci.pse.dev/docs/contributing) and [code of conduct](https://maci.pse.dev/docs/contributing/code-of-conduct).
- [ ] I have read and understand MACI's [GitHub processes](https://github.com/privacy-scaling-explorations/maci/discussions/847).
- [ ] I have read and understand MACI's [testing guide](https://maci.pse.dev/docs/testing).

2024-10-25 17:41 UTC, 0xmad requested changes
@programmerraja thanks, there are some changes requested

2024-10-25 17:41 UTC, 0xmad commented on scripts/generateMaciKeys.js
Please use typescript

2024-10-25 17:41 UTC, 0xmad commented on scripts/generateMaciKeys.js
> +  const outputDir = path.join(__dirname, "..", "maci-keys");
```suggestion
  const outputDir = path.resolve(__dirname, "..", "maci-keys");
```

2024-10-25 17:41 UTC, 0xmad commented on scripts/generateMaciKeys.js
> +  const outputFile = path.join(outputDir, "maci-keys.json");
```suggestion
  const outputFile = path.resolve(outputDir, "maci-keys.json");
```

2024-10-25 17:41 UTC, 0xmad commented on scripts/generateMaciKeys.js
> +  }
Use async version here

2024-10-25 17:41 UTC, 0xmad commented on scripts/generateMaciKeys.js
> +  fs.writeFileSync(outputFile, JSON.stringify(keys, null, 2));
The same with async

2024-10-26 03:44 UTC, programmerraja commented
@0xmad can you check and let me know anything else i want to change

2024-10-28 14:51 UTC, 0xmad commented on scripts/generateMaciKeys.ts
> +import * as path from "path";
```suggestion
import fs from "fs";
import path from "path";
```

2024-10-28 14:55 UTC, ctrlc03 reviewed
I'm not sure writing coordinator keys to disk is something we should be encouraging. I'd probably only let the script print to console (basically just call the cli script using pnpm: `node build/ts/index.js genMaciKeyPair`)

2024-10-28 14:59 UTC, programmerraja commented on scripts/generateMaciKeys.ts
> +    await fs.access(outputDir);
@0xmad done can you check

2024-11-01 04:05 UTC, programmerraja commented
@0xmad is everything fine or did i need to do any changes?

2024-11-01 14:33 UTC, 0xmad commented
> I'm not sure writing coordinator keys to disk is something we should be encouraging. I'd probably only let the script print to console (basically just call the cli script using pnpm: `node build/ts/index.js genMaciKeyPair`)

@programmerraja here is a question and also there are failed ci jobs.

2024-11-01 14:36 UTC, programmerraja commented
@0xmad can you give me guidance what next I need to do

2024-11-28 23:13 UTC, crisgarner commented
Hello @programmerraja thanks for working on this, anything else you need assistance with?

2025-01-08 10:54 UTC, ctrlc03 commented
Thank you for your interest to contribute to MACI. While we appreciate this PR, due to inactivity and a recent submission for the same issue (https://github.com/privacy-scaling-explorations/maci/pull/1992), we will be closing this PR. We look forward to your future contributions, please get in touch if you would like to take an issue but not sure which one to tackle.

2025-01-08 10:54 UTC, closed without merging