test(contracts): re-organize smart contract tests in separate files
privacy-scaling-explorations/maci pull request #897
Opened 2023-12-11 10:56 UTC by ctrlc03

Currently all tests related to a Poll were inside one file (MACI.test) - these tests have been moved into their respective files, re organized and cleaned up, and a small number of test cases were added which were missing.

re #843

2023-12-11 15:14 UTC, baumstern requested changes
Great work! Just left a nitpick

2023-12-12 06:05 UTC, baumstern commented on contracts/contracts/Poll.sol
> +  bool public isInit;
Isn't L84:85 is redundant?:
https://github.com/privacy-scaling-explorations/maci/blob/050e7887fdf381b6d715abec87eab8d0567b1d03/contracts/tests/Poll.test.ts#L84-L85

L87 checks same condition what L84:85 does:
https://github.com/privacy-scaling-explorations/maci/blob/050e7887fdf381b6d715abec87eab8d0567b1d03/contracts/tests/Poll.test.ts#L87

2023-12-12 09:18 UTC, kittybest commented on contracts/tests/Poll.test.ts
> +  it("should not be possible to init the Poll contrac twice", async () => {
typo: contract

2023-12-12 09:43 UTC, ctrlc03 commented on contracts/contracts/Poll.sol
> +  bool public isInit;
sure I see what you mean, fixing now

2023-12-12 10:01 UTC, baumstern approved these changes
Looks good to me! I'll leave it open for @kittybest to take a peek

2023-12-14 09:07 UTC, kittybest approved these changes

2023-12-14 09:50 UTC, merged