chore(website): cut down /roadmap length
privacy-scaling-explorations/maci pull request #939
Opened 2023-12-21 05:55 UTC by samajammin

# Description

Shortened this up to focus on core priorities & tighten language

## Related issue(s)

#857 

## Confirmation

- [x] I have read and understand MACI's [contributor guidelines](https://github.com/privacy-scaling-explorations/maci/blob/dev/CONTRIBUTING.md) and [code of conduct](https://github.com/privacy-scaling-explorations/maci/blob/dev/CODE_OF_CONDUCT.md).
- [x] I have read and understand MACI's [GitHub processes](https://github.com/privacy-scaling-explorations/maci/discussions/847).
- [x] I have read and understand MACI's [testing guide](https://maci.pse.dev/docs/testing).

2023-12-27 15:19 UTC, ctrlc03 requested changes
Lgtm just one question

2023-12-27 15:19 UTC, ctrlc03 commented on website/src/pages/roadmap.md
> +2. ~~2023: MACI integrated by a PSE project~~ (✅, [QFI](https://github.com/privacy-scaling-explorations/qf))
Do we change this short hand link to 'qf'?

2023-12-27 16:57 UTC, kittybest approved these changes

2023-12-27 17:16 UTC, ctrlc03 approved these changes

2023-12-27 19:02 UTC, merged

2023-12-30 16:12 UTC, daodesigner commented
Nice +1 on removing the accomplishments and projects from unrelated product teams you were not a part of from the MACI roadmap!